//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuilderServiceClient.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IBuildService")]
    public interface IBuildService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildService/Build", ReplyAction="http://tempuri.org/IBuildService/BuildResponse")]
        System.IO.Stream Build(string projectId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildService/Build", ReplyAction="http://tempuri.org/IBuildService/BuildResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> BuildAsync(string projectId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildServiceChannel : BuilderServiceClient.Services.IBuildService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildServiceClient : System.ServiceModel.ClientBase<BuilderServiceClient.Services.IBuildService>, BuilderServiceClient.Services.IBuildService {
        
        public BuildServiceClient() {
        }
        
        public BuildServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream Build(string projectId) {
            return base.Channel.Build(projectId);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> BuildAsync(string projectId) {
            return base.Channel.BuildAsync(projectId);
        }
    }
}
